name = "MathlibDemo"
defaultTargets = ["MathlibDemo"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.25.0-rc2"

[[lean_lib]]
name = "MathlibDemo"
